services: 
    gunicorn:
        image: backend
        ports: 
            - "8000:8000"
    

    nginx: 
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - /../nginx:/etc/nginx
            - /etc/letsencrypt:/etc/letsencrypt
            - ./twitter_clone/static:/usr/share/nginx/static



            