services: 
    gunicorn:
        build: ./twitter_clone
        ports: 
            - "8000:8000"
    

    nginx: 
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - /etc/nginx:/etc/nginx  
            - ./twitter_clone/static:/usr/share/nginx/static/
            - /etc/letsencrypt:/etc/letsencrypt



            