services: 
    gunicorn:
        build: ./twitter_clone
        ports: 
            - "8000:8000"
    

    nginx: 
        image: nginx
        ports: 
            - "80:80"
        volumes:
            - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf   
            - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
            - /etc/nginx/sites-available:/etc/nginx/sites-available
            - ./twitter_clone/static:/usr/share/nginx/static/



            