# Generated by Django 3.0.8 on 2020-07-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0004_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
