# Generated by Django 3.0.8 on 2020-07-18 23:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0006_follow_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='make_posts.Follower'),
        ),
    ]
