# Generated by Django 3.0.8 on 2020-07-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0014_auto_20200724_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
