# Generated by Django 3.0.8 on 2020-07-30 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0017_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='make_posts.Post'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
