# Generated by Django 3.0.8 on 2020-07-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0018_auto_20200730_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
