# Generated by Django 3.0.8 on 2020-07-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_posts', '0019_auto_20200730_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
